In [6]:
import pandas as pd
import numpy as np

data = pd.read_excel('all_label.xlsx')

features = data.iloc[:, :8].values
labels = data.iloc[:, 8].values

In [7]:
features

array([[1.15470639e-01, 1.61738766e-01, 8.72375083e-04, 2.21420293e-03,
        3.13108249e-04, 1.13971896e-03, 8.01633437e-04, 2.41643254e-03],
       [8.23094120e-04, 2.67972264e-03, 1.15531807e-01, 1.62396213e-01,
        8.53871156e-04, 2.11213427e-03, 3.76471088e-04, 1.04146593e-03],
       [1.54687332e-04, 1.15880751e-03, 8.45601888e-04, 2.54602836e-03,
        1.15364463e-01, 1.62475006e-01, 9.50962131e-04, 1.91652272e-03],
       [7.28993267e-04, 2.20024749e-03, 5.43223157e-04, 1.21689756e-03,
        8.47795040e-04, 2.42491241e-03, 1.14744636e-01, 1.62084528e-01],
       [1.19228348e-01, 1.68744504e-01, 1.18922528e-01, 1.69253022e-01,
        1.18781822e-01, 1.69424793e-01, 1.18840317e-01, 1.69098450e-01],
       [1.21673961e-01, 1.73668596e-01, 4.09260315e-02, 8.01658266e-04,
        1.21654736e-05, 6.51972959e-04, 1.55214292e-03, 3.21370019e-02],
       [1.70110378e-03, 3.25082524e-02, 1.21618576e-01, 1.74618869e-01,
        4.01904039e-02, 4.52830685e-04, 1.16336713e-04, 9.

In [8]:
labels

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 6, 6, 6, 6, 6, 6, 6,
       6, 6, 6, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 8, 8, 8, 8, 8, 8, 8, 8, 8,
       8], dtype=int64)

In [9]:
# 添加偏置项
features = np.c_[np.ones(features.shape[0]), features]

# 计算参数 theta
theta = np.linalg.inv(features.T @ features) @ features.T @ labels

theta

array([ 3.18085333,  4.161494  , -2.94294313,  4.15450312, -2.93938571,
        4.17028487, -2.94862266,  4.17104667, -2.94956333])

In [11]:
# 预测
data2 = pd.read_excel('test_label.xlsx')

test_features = data2.iloc[:, :8].values
test_features = np.c_[np.ones(test_features.shape[0]), test_features]
predictions = np.dot(test_features, theta)

# 输出预测结果
predictions

array([3.2365811 , 3.23352275, 3.23315764, 3.28365016, 3.28823938,
       3.28503694, 3.28455257, 3.30169318, 3.30638494, 3.30313044,
       3.30261744, 3.3578373 , 3.36281815, 3.35939801, 3.3588252 ,
       3.377098  , 3.38216999, 3.37869198, 3.37810658, 3.68413971,
       3.69039322, 3.68595351, 3.68544026, 3.87687263, 3.88374351,
       3.8786828 , 3.87834112, 4.48361028, 4.49221686, 4.48518068,
       4.48559234, 8.96957481, 8.9894956 , 8.96792382, 8.97542886])